Repository hmcts/reform-scan-notification-service, pull requests merged in 2020-05, with the labels that each got.

#118 Bump log4j 2.12.1 -> 2.13.2
  build.gradle
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-118

#124 remove staging specific queue config
  charts/reform-scan-notification-service/Chart.yaml
  charts/reform-scan-notification-service/values.aat.template.yaml
  charts/reform-scan-notification-service/values.yaml
  src/main/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-124

#132 Remove deprecated flag for installing chart
  Jenkinsfile_CNP
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-132

#131 add staging db infra
  infrastructure/main.tf
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-131

#134 add staging secrets
  charts/reform-scan-notification-service/values.aat.template.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-134

#136 fix staging db conf
  src/main/resources/bootstrap.yaml
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-136

#137 search notification by date
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-137

#139 add id to notification response
  src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/ProcessNotificationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/model/out/NotificationInfo.java
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-139

#140 add notification end point
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationController.java
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-140

#141 cleanup integration test
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/ControllerTestBase.java
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-141

#149 Added ilbIp var as the terraform module enforces to set the value
  infrastructure/variables.tf
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-149

#154 Upgrade tomcat embedded jars due to CVE-2020-9484
  build.gradle
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-154

#147 Copy test s2s secret
  infrastructure/main.tf
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-147

#156 Fix resource group for s2s vault
  infrastructure/main.tf
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-156

#153 Use new secret in pipeline for functional tests
  Jenkinsfile_CNP
  src/functionalTest/resources/servicebus/message/valid-notification.json
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-153

#155 Bump java chart 2.15 -> 2.18
  charts/reform-scan-notification-service/Chart.yaml
  charts/reform-scan-notification-service/requirements.yaml
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-155

#160 Bump gradle 6.2.2 -> 6.4.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:reform-scan, rel:reform-scan-notification-service-pr-160
