Repository hmcts/reform-scan-notification-service, pull requests merged in 2021-02, with the labels that each got.

#386 avoid netty vulnerability
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-386

#382 DTSBPS-369: bump springboot 2.4.3
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-382

#389 Bump postgresql from 42.2.14 to 42.2.19 #383
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-389
