Repository hmcts/reform-scan-notification-service, pull requests merged in 2021-09, with the labels that each got.

#597 Code smells
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/AuthServiceTest.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageMapperTest.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParserTest.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTaskTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-597

#600 DTSBPS-749 suppress vulnerability
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-600

#601 bump to azure-messaging-servicebus 7.4.1
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-601

#611 bump versions-failed depabot PRs
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-611
