Repository hmcts/reform-scan-notification-service, pull requests merged in 2021-08, with the labels that each got.

#570 DTSBPS-695 remove feign exception creation
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-570

#573 DTSBPS-687: fortify integration on nightly build
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-573

#574 DTSBPS-706 use git native dependabot
  .dependabot/config.yml
  .github/dependabot.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-574

#578 /all-pending endpoint
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-578

#588 DTSBPS-722 fix terraform error
  infrastructure/state.tf
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-588
