Repository hmcts/reform-scan-notification-service, pull requests merged in 2021-12, with the labels that each got.

#668 DTSBPS-804 upgrade spring boot 2.6.1
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-668

#673 Bump log4j version
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-673

#684 Updated fortify release id
  config/fortify-client.properties
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-684
