Repository hmcts/reform-scan-notification-service, pull requests merged in 2022-08, with the labels that each got.

#962 Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-962

#966 Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-966

#967 Add backstage configuration file
  catalog-info.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-967
