Repository hmcts/reform-scan-notification-service, pull requests merged in 2022-06, with the labels that each got.

#856 DTSBPS-960: Suppress CVE-2022-22976
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-856

#865 DTSBPS-978: Fix CVE 2022 22978
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-865

#866 Removed suppressions
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-866

#889 Suppress CVE-2022-34305
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-889
