Repository hmcts/reform-scan-notification-service, pull requests merged in 2022-10, with the labels that each got.

#1048 Add suppression for tomcat libraries
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1048

#1053 Suppress CVE-2022-42003 and CVE-2022-42004 (DTSBPS-1109)
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1053

#1069 Upgraded junit-jupiter
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1069
