Repository hmcts/reform-scan-notification-service, pull requests merged in 2022-07, with the labels that each got.

#891 Suppress CVE-2022-33915
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-891

#906 Suppress CVE-2022-31569
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-906

#907 Bump java chart version
  charts/reform-scan-notification-service/Chart.yaml
  charts/reform-scan-notification-service/values.preview.template.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-907

#912 DTSBPS-1020: Pinned azureem version
  infrastructure/state.tf
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-912
