Repository hmcts/reform-scan-notification-service, pull requests merged in 2022-05, with the labels that each got.

#826 Resolve CVE-2022-24823 (DTSBPS-943)
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-826

#827 Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-827

#828 Suppress CVE-2022-29885 (DTSBPS-947)
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-828
