Repository hmcts/reform-scan-notification-service, pull requests merged in 2022-11, with the labels that each got.

#1098 Suppress Spring-security and tomcat-embed vulnerabilities (DTSBPS-1143)
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1098

#1127 DTSBPS-1163: Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1127

#1130 DTSBPS-1167: Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1130
