Repository hmcts/reform-scan-notification-service, pull requests merged in 2023-01, with the labels that each got.

#1205 DTSBPS-1235: Suppressed CVE-2021-4277
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1205

#1212 DTSBPS-1236: Suppressed dependencies
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1212

#1246 DTSBPS-1258: Upgraded AppInsights to the latest version
  Dockerfile
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1246

#1251 DTSBPS-1276: cleanup suppressions
  config/owasp/suppressions.xml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1251
