Repository hmcts/reform-scan-notification-service, pull requests merged in 2023-03, with the labels that each got.

#1312 DTSBPS-1325: Fix CVE 2023 24998
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, no-changes, rel:reform-scan-notification-service-pr-1312

#1324 Local dev
  .gitignore
  docker-compose.yml
  docker/database/Dockerfile
  docker/database/init-db.sh
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1324

#1360 Local dev
  .env
  config/owasp/suppressions.xml
  docker-compose.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1360
