Repository hmcts/reform-scan-notification-service, pull requests merged in 2024-09, with the labels that each got.

#1606 FACT-1980 - CVE and Dependency Updates
  .github/dependabot.yml
  build.gradle
  charts/reform-scan-notification-service/Chart.yaml
  config/owasp/suppressions.xml
  infrastructure/state.tf
Labels: ns:reform-scan, prd:reform-scan, aat/add-or-update, prod/add-or-update, rel:reform-scan-notification-service-pr-1606

#1607 FACT-1802 17 to 21 changes
  .github/workflows/ci.yml
  .github/workflows/publish-openapi.yaml
  Dockerfile
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/resources/application.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1607

#1618 FACT-1802 added missing flyway version variable
  .gitignore
  build.gradle
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1618
