Repository hmcts/reform-scan-notification-service, pull requests merged in 2024-06, with the labels that each got.

#1559 FACT-1792 - open API
  .github/workflows/publish-openapi.yaml
  .github/workflows/swagger.yml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1559

#1560 Updated azurerm
  infrastructure/state.tf
Labels: ns:reform-scan, prd:reform-scan, aat/add-or-update, prod/add-or-update, rel:reform-scan-notification-service-pr-1560

#1577 adding migration only for demo
  src/main/resources/db/migration/V010__add_calling_client.sql
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1577

#1579 Update README.md
  README.md
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1579

#1574 Fact 1819
  charts/reform-scan-notification-service/Chart.yaml
  charts/reform-scan-notification-service/values.preview.template.yaml
  charts/reform-scan-notification-service/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/clients/ErrorNotificationClientTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
  src/integrationTest/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/notificationservice/clients/ErrorNotificationClientSecondary.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/clients/ErrorNotificationConfigurationSecondary.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/config/SecondaryClientJurisdictionsConfig.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/config/jms/JmsReceivers.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/data/NewNotification.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/data/Notification.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationMapper.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/service/JmsNotificationMessageProcessor.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageHandler.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageMapper.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageMapperTest.java
  src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1574

#1580 FACT-1828 DB script
  src/main/resources/db/migration/V011__set_client_not_null.sql
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1580

#1581 updates j21 build gradle
  Dockerfile
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1581

#1582 fix
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1582
