Repository hmcts/reform-scan-notification-service, pull requests merged in 2024-03, with the labels that each got.

#1536 FACT-1632 switch to use flex creds
  charts/reform-scan-notification-service/Chart.yaml
  charts/reform-scan-notification-service/values.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1536

#1537 spingboot 3 initial changes
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/JmsNotificationsMessageSender.java
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/config/SwaggerPublisher.java
  src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/health/ReadinessTest.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/Application.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/config/HttpConfiguration.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/config/jms/JmsConfiguration.java
  src/main/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTask.java
  src/main/resources/application-dev.yaml
Labels: ns:reform-scan, prd:reform-scan, rel:reform-scan-notification-service-pr-1537

#1545 Setup read only access for single server
  infrastructure/main.tf
Labels: ns:reform-scan, prd:reform-scan, add-or-update, rel:reform-scan-notification-service-pr-1545

#1544 recreate roles/access
  infrastructure/tf-db-flexible.tf
Labels: ns:reform-scan, prd:reform-scan, destroy, rel:reform-scan-notification-service-pr-1544

#1543 schema ownership fix [DO NOT MERGE TILL RELEASE] #2189
  infrastructure/tf-db-flexible.tf
Labels: ns:reform-scan, prd:reform-scan, add-or-update, rel:reform-scan-notification-service-pr-1543
